// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFAsJN0us5bN_FZ5TXUB82rWdjfM-KfJM',
    appId: '1:860460354273:web:eb2e751257b3aef74e45a0',
    messagingSenderId: '860460354273',
    projectId: 'dallimon',
    authDomain: 'dallimon.firebaseapp.com',
    storageBucket: 'dallimon.firebasestorage.app',
    measurementId: 'G-M7SHZSYSGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFGogqHaROBR4XpdQ0XxVlsV6X1Qz-9Xw',
    appId: '1:860460354273:android:e77c792585a06d2f4e45a0',
    messagingSenderId: '860460354273',
    projectId: 'dallimon',
    storageBucket: 'dallimon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxja6xnaVO9Qi29PZOSI0_BaenG0z425Y',
    appId: '1:860460354273:ios:10397b98798cc99a4e45a0',
    messagingSenderId: '860460354273',
    projectId: 'dallimon',
    storageBucket: 'dallimon.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxja6xnaVO9Qi29PZOSI0_BaenG0z425Y',
    appId: '1:860460354273:ios:10397b98798cc99a4e45a0',
    messagingSenderId: '860460354273',
    projectId: 'dallimon',
    storageBucket: 'dallimon.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFAsJN0us5bN_FZ5TXUB82rWdjfM-KfJM',
    appId: '1:860460354273:web:b367d1c43152a3564e45a0',
    messagingSenderId: '860460354273',
    projectId: 'dallimon',
    authDomain: 'dallimon.firebaseapp.com',
    storageBucket: 'dallimon.firebasestorage.app',
    measurementId: 'G-C2QCVVVP2M',
  );
}
